local BAR_HEIGHT = 28
local ITEM_HEIGHT = BAR_HEIGHT - 8
local WS_FONT_SIZE = math.floor(BAR_HEIGHT * 0.5)
local WS_WIDTH = BAR_HEIGHT - 8
local APP_ICON_SCALE = ITEM_HEIGHT / 32

return {
  BAR_HEIGHT = BAR_HEIGHT,
  ITEM_HEIGHT = ITEM_HEIGHT,
  ITEM_OFFSET = -math.floor(ITEM_HEIGHT / 2) + 1,
  WS_FONT_SIZE = WS_FONT_SIZE,
  WS_WIDTH = WS_WIDTH,
  APP_ICON_SCALE = APP_ICON_SCALE,
}
