#!/usr/bin/env lua
package.cpath = package.cpath .. ";/Users/" .. os.getenv("USER") .. "/.local/share/sketchybar_lua/?.so"

local sbar = require("sketchybar")

require("theme").load("tokyodark")

sbar.begin_config()

require("init")

sbar.hotload(true)
sbar.end_config()
sbar.event_loop()
